### ISSUE TITLE
Undefined function or variable 'refineNVBModified'.

### ISSUE THREAD

**Issue by Batmanabcdefg** [sadda/Helmholtz#1]
**_Undefined function or variable 'refineNVBModified'._**

Error in Main (line 121)
                [coordinates, elements, dataToProlong, dirichlet,
                neumann] = refineNVBModified(coordinates, elements,
                dataToProlong, dirichlet, neumann,
                logical(markedTriangles));

**Comment by sadda** [comment]
Thanks for the comment. I made a mistake in gitignore and the files were not uploaded. It should be fine now :)
